export { default as PostCard } from './PostCard'
export { default as Categories } from './Categories'
export { default as PostWidget } from './PostWidget'
export { default as Header } from './Header'
export { default as Layout } from './Layout'
export { default as PostDetail } from './PostDetail'
export { default as Author } from './Author'
export { default as CommentsForm } from './CommentsForm'
export { default as Comments } from './Comments'
export {default as FeaturedPostCard } from './FeaturedPostCard'
export {default as Header1 } from './Header1'
export {default as Header2 } from './Header2'
export {default as Banner } from './Banner'
export {default as Footer } from './Footer'
export {default as Landingone } from './Landingone'
export {default as Landingtwo } from './Landingtwo'
export {default as Newsletter } from './Newsletter'
export {default as NewsletterForm } from './NewsletterForm'
export {default as Ourteam } from './Ourteam'

